default:
  outputs:
    dev:
      dataset: dbt_rides
      method: service-account
      project: production-yummy
      threads: 4
      type: bigquery
      # Para Cloud Run, intentar치 usar GOOGLE_APPLICATION_CREDENTIALS si est치 disponible
      # De lo contrario, usar치 la autenticaci칩n predeterminada de Google Cloud
  target: dev
